"""Color pair constants used as style identifiers by render.py."""

CP_USER_NAME = 1
CP_CHAR_NAME = 2
CP_SYSTEM_NAME = 3
CP_REASONING = 4
CP_SWIPE_INDICATOR = 5
CP_HELP_BAR = 6
CP_SEPARATOR = 7
CP_TIMESTAMP = 8
CP_CURSOR_MARKER = 9
CP_TITLE_BAR = 10
CP_PROGRESS_FILL = 11
CP_META = 12
CP_SEARCH_MATCH = 13
